### ISSUE TITLE
Morning session: peer to peer code review

### ISSUE THREAD

**Issue by Tessyrich** [Feliverse/conference-page#4]
### Peer to Peer code review

We thank you @Feliverse for sharing your code with us.
You have done a wonderful job so far, but there are some areas you need to make corrections to.

- Kindly check your identation on html files, it will be better if is only 2 spaces, according best practices.

- Kindly use the font reference inside the .css file, according best practices.

- Kindly use % or Rem while giving widths to your section as this will make it more responsive.

**Comment by Feliverse** [comment]
Thank you, Tessy and partners,
my code looks better now, I puts in practice all your recomendations.
